version: '2'
services:
  contacto-app:
    image: contacto
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:mariadb://contacto-mariadb:3306/contacto
      - JHIPSTER_SLEEP=120 # gives time for mariadb server to start
    ports:
      - 8080:8080
  contacto-mariadb:
    extends:
      file: mariadb.yml
      service: contacto-mariadb
